files:
- file: io.py
  plugins:
  - name: fileread
    class_name: FileReadMod
  - name: stdout
    class_name: StdoutMod
- file: funcs.py
  plugins:
  - name: add
    class_name: AddMod
  - name: alu
    class_name: ALUMod
